import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta  name="viewport" content="width=device-width, initial-scale=1.0"  />
      <body
        className={`antialiased`}
      >
        <div id="modal-root"></div>
        <Header/>
        {children}
      </body>
    </html>
  );
}
